### ISSUE TITLE
Issue-1-user-can-search-for-a-film

### ISSUE THREAD

**Issue by TyStahl** [TyStahl/Casting-Recall#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a film

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user will land on the landing page and be able to search for a film by inputting text into the text input form.

The plan is to style the page appropriately for mobile and desktop and then to add an event listener to capture the users search term and compare it to the api data to find an exact match. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Mobile Landing Page](https://github.com/TyStahl/ajax-project/assets/57151242/41317b15-f3f1-480e-8e09-ae376a908c0b)
![Mobile Search Page](https://github.com/TyStahl/Casting-Recall/assets/57151242/11dc6b72-12de-4555-90b2-8ad50cc2223f)
![Desktop Landing Page](https://github.com/TyStahl/Casting-Recall/assets/57151242/d46b0c08-f544-4022-908f-2fd2ceb34ffa)
![Desktop Search Page](https://github.com/TyStahl/Casting-Recall/assets/57151242/9c2027d5-d85b-43a0-8d8b-ee348759d4bb)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Style the page to react dynamically for mobile and desktop
- [x] add an event listener to the input text box
- [x] define a  callback function  which assigns the term captured to a variable.
- [x] console log the variable to ensure it saves the term properly
- [x] create a html skeleton with unordered list with placeholders in the appropriate places to model the landing page and movie search page
- [x] define a function which compares the search term variable to the api data object
- [x] create data model to handle rendering api data in dom tree
- [x] define a function to render the dom tree populated with data from the api to match the reference html skeleton
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
