### ISSUE TITLE
Issue-2-user-can-view-cast

### ISSUE THREAD

**Issue by TyStahl** [TyStahl/Casting-Recall#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to click on a movie card generated by their search and exit the page showing the search results, moving to a page showing top cast members with the option to "swap out" actors or actresses in chosen roles. The name of the actor/actress and the stock image of the actor/actress would be replaced by the chosen actor/actress in the position of the role they have selected.

User can view the cast of a movie they select and recast the roles.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user will be able to search for a film, click on the film card to enter a page showing the cast, then they would be able to click on an actors card to update it with information about an actor of their choosing.

Implement a view swap functionality moving between a populated list of movies, and a populated list of cast members of movie using the individual movies id attribute, and a populated list of actors/actresses 'people'.

Implement navigation anchors between views

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Mobile Cast Information Page](https://github.com/TyStahl/Casting-Recall/assets/57151242/fed1c3af-4807-4ec4-ac23-fc6fd88421ef)
![Mobile Peoples Search Page](https://github.com/TyStahl/Casting-Recall/assets/57151242/8e6a011a-b411-4b83-af8b-fe5c69110600)
![Desktop Cast Information Page](https://github.com/TyStahl/Casting-Recall/assets/57151242/fd88b678-427f-4f05-a1ce-230a1f3aeae9)
![Desktop Peoples Search Page](https://github.com/TyStahl/Casting-Recall/assets/57151242/4f3ecff2-8a71-43ca-9938-41974b6c7c97)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Generate necessary html and css to reflect additional view pages
- [x] add cast array to data model for generating list of cast members
- [x] Add people array to data model for generating list of actors
- [x] implement a view swap landing page, 
- [x] view swap movie search page, 
- [x] view swap movie cast page, 
- [x] define new click event listener and callback function which retrieves movie id from the movies array and view swaps to cast page
- [x] add new xmlhttprequest for details of movie cast using movie id
- [x] define new render function for cast dom tree
- [x] define new render function for peoples dom tree
- [x] define new click event listener for 'swap button'  on cast information cards
- [x] add new xmlhttprequest for search of peoples 
- [x] add new click event listener for 'select' anchor on peoples information cards
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
